# Generated by Django 5.2.4 on 2025-08-26 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
        ('stock', '0002_inventorytransaction_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransferrequest',
            name='dispatched_lot',
            field=models.ForeignKey(blank=True, help_text='The specific lot from which stock was dispatched.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_dispatches', to='stock.lotserialnumber'),
        ),
    ]
