# Generated by Django 5.2.4 on 2025-08-26 16:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobcost',
            options={'verbose_name': 'Job Cost', 'verbose_name_plural': 'Job Costs'},
        ),
        migrations.AddField(
            model_name='jobcost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobcost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name='jobcost',
            table='inventory_job_cost',
        ),
    ]
