"""
Django settings for inventory_system project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os

BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

SECRET_KEY = 'django-insecure-@1j3+^r%c%r90a07+9j+8&p_!9s!a+c!#g0q0%6#3h(r^q_w*v'
DEBUG = True
ALLOWED_HOSTS = []

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    
    'dbbackup',
    'crispy_forms',
    'crispy_bootstrap5',
    'import_export',

    # My Custom Apps
    'products',
    'partners',
    'stock',
    'purchase',
    'sales',
    'pos',
    'costing',
    'reports',
    'accounts',
    'management',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',

    'management.middleware.IPWhitelistMiddleware',

    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'inventory_system.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'inventory_system', 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'inventory_system.wsgi.application'

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static & Media Files
STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles_production')
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom user model & Login/Logout redirects
AUTH_USER_MODEL = 'accounts.User'
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'login'

# Crispy Forms settings
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# DBBackup Settings (লোকাল ব্যাকআপের জন্য)
DBBACKUP_STORAGE = 'django.core.files.storage.FileSystemStorage'
DBBACKUP_STORAGE_OPTIONS = {'location': os.path.join(BASE_DIR, 'backups')}

# Custom Global Constants
DEFAULT_CURRENCY_SYMBOL = 'QAR '

# Password Hashers (Argon2 first, fallback to others)
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
]

# Session & CSRF Security
SESSION_COOKIE_SECURE = True          # কুকি শুধু HTTPS এ পাঠানো হবে
CSRF_COOKIE_SECURE = True             # CSRF কুকি শুধু HTTPS এ পাঠানো হবে
SESSION_COOKIE_HTTPONLY = True        # JavaScript session cookie পড়তে পারবে না
CSRF_COOKIE_HTTPONLY = True           # JavaScript CSRF cookie পড়তে পারবে না
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # ব্রাউজার বন্ধ হলে লগআউট হবে
SESSION_COOKIE_AGE = 1800             # সেশন ৩০ মিনিট পর auto expire হবে (সেকেন্ডে)

# IP Whitelisting Settings
ALLOWED_IPS = [
    '127.0.0.1',  # লোকাল ডেভেলপমেন্টের জন্য
    '192.168.1.101', # অফিসের একটি নির্দিষ্ট কম্পিউটারের আইপি 
    '203.0.113.5',   # অন্য কোনো শাখার পাবলিক আইপি  এড্রেস আপডেট করে দিলে হবে।
]

# Email Configuration for Password Reset
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'haymijan@gmail.com'  # আপনার জিমেইল অ্যাড্রেস
EMAIL_HOST_PASSWORD = 'vfjp hmho onkd tjun' # আপনার জিমেইল অ্যাপ পাসওয়ার্ড

# যে ইমেইল থেকে ব্যবহারকারী ইমেইল পাবে
DEFAULT_FROM_EMAIL = 'haymijan@gmail.com'