# Generated by Django 5.2.4 on 2025-08-27 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_salesreturn_salesreturnitem'),
        ('stock', '0002_inventorytransaction_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderitem',
            name='lot_serial',
            field=models.ForeignKey(blank=True, help_text='The specific lot this item was sold from.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.lotserialnumber'),
        ),
    ]
