# Generated by Django 5.2.4 on 2025-08-28 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_salesorderitem_lot_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesreturnitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price of the item at the time of return.', max_digits=10),
        ),
    ]
