# Generated by Django 5.2.4 on 2025-08-30 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_salesreturnitem_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderitem',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost of the product at the time of sale.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
    ]
